Fix CompileError due to default values and multiple clauses
On Elixir 0.14.3, compilation fails with the following message:

  == Compilation error on file lib/chronos.ex ==
  ** (CompileError) lib/chronos.ex:165: def days_ago/2 has default values
     and multiple clauses, define a function head with the defaults
      (elixir) src/elixir_def.erl:336: :elixir_def.store_each/8
      (elixir) src/elixir_def.erl:107: :elixir_def.store_definition/9
      lib/chronos.ex:165: (module)
      (stdlib) erl_eval.erl:657: :erl_eval.do_apply/6
      (elixir) src/elixir.erl:170: :elixir.erl_eval/3

This is due to a change from elixir-lang/elixir#2467